version: 2
registries:
  rubygems-server-rubygems-pkg-github-com:
    type: rubygems-server
    url: https://rubygems.pkg.github.com
    token: "${{secrets.RUBYGEMS_SERVER_RUBYGEMS_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  registries:
  - rubygems-server-rubygems-pkg-github-com
